baseURL: "https://ccream.github.io/crmcc/"
languageCode: "en-us"
title: "Jiasen's Homepage"
theme: 
  - "PaperMod"



menu:
  main:
    - identifier: about
      name: "About"
      url: "/about"
      weight: 1
    - identifier: research
      name: "Research"
      url: "/research/"
      weight: 2