baseURL: "https://ccream.github.io/crmcc/"
languageCode: "en-us"
title: "Jiasen's Homepage"
theme: 
  - "PaperMod"



menu:
  main:
    - identifier: about
      name: "About"
      url: "/about"
      weight: 1
    - identifier: research
      name: "Research"
      url: "/research/"
      weight: 2
    - identifier: notes
      name: "Notes"
      url: "/notes/"
      weight: 3
    - identifier: reading
      name: "Reading"
      url: "/reading/"
      weight: 4
    - identifier: cv
      name: "CV"
      url: "/cv/"
      weight: 5
